# Generated by Django 3.0.6 on 2021-05-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincoupechef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='begin_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
