# Generated by Django 3.0.6 on 2021-05-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincoupechef', '0002_auto_20210508_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edition',
            name='programmed',
            field=models.BooleanField(default=False),
        ),
    ]
