# Generated by Django 3.0.6 on 2021-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincoupechef', '0003_auto_20210508_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abreviation',
            field=models.CharField(default='team', max_length=50),
        ),
    ]
