# Generated by Django 3.0.6 on 2021-05-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincoupechef', '0004_team_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
