# Generated by Django 3.0.6 on 2021-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincoupechef', '0005_match_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matricule',
            field=models.CharField(default='00000', max_length=20, null=True),
        ),
    ]
