# Generated by Django 3.0.6 on 2020-12-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puser.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('M', 'MASCULIN'), ('F', 'FEMININ'), ('I', 'INDETERMINATE')], default='I', max_length=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('confirm_code', models.CharField(default='0000', max_length=8)),
                ('renitialisation_code', models.CharField(default='0000', max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('utype', models.CharField(default='user', max_length=30, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('profil', models.CharField(default='default.png', max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='puser/profils/%Y/%m/%d/')),
                ('pseudo', models.CharField(blank=True, max_length=200, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(default='19.3.202.3')),
                ('baned', models.BooleanField(default=False, help_text='allow us to know if used where baned nor not')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puser.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
