# Generated by Django 3.0.6 on 2021-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puser', '0002_auto_20210108_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
